name: Build Vinted API

on:
  workflow_dispatch:

  push:
    paths:
      - "results/**"
      - "build_api.py"
      - "site/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build JSON API
        run: python build_api.py

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages site
        uses: actions/upload-pages-artifact@v3
        with:
          path: site


  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
