name: Vinted Trend Search

on:
  workflow_dispatch:
    inputs:
      search:
        description: "Vinted search keyword"
        required: true
        default: "running t shirt men"
        type: string

      pages:
        description: "Number of pages to scan"
        required: true
        default: "5"
        type: string

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: |
          echo "Search: ${{ inputs.search }}"
          echo "Pages: ${{ inputs.pages }}"
